default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: desenv
  password: 123456789

development:
  <<: *default
  database: caronasbraz_api_development

test:
  <<: *default
  database: caronasbraz_api_test

production:
  <<: *default
  database: caronasbraz_api_production

